version: '3.9'

services:
  postgre1:
    container_name: laba5
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=laba5
    ports:
      - "5437:5432"
    restart: unless-stopped

  postgres2:
    container_name: gateway
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gateway
    ports:
      - "5439:5432"
    restart: unless-stopped

  postgres3:
    container_name: lab5
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lab5
    ports:
      - "5438:5432"
    restart: unless-stopped