version: '3.9'

services:
  postgres:
    container_name: lab3
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lab3
    ports:
      - "5432:5432"
    restart: unless-stopped